# -*- coding: utf-8 -*-
"""Climate_Risk_Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oP3DdBC7PlFOcjMCossaC4C1OI7IHOOm
"""

# 📦 Step 1: Install required packages
!pip install folium geopy requests tensorflow sklearn matplotlib
!pip install -q transformers

# 🔐 Step 2: API Keys and Setup
import os

# Replace with your actual API keys
OPENCAGE_API_KEY = "c8d01cd61ff84ca5ac8cb56bf550e2b6"
WEATHER_API_KEY = "339cbb5eb260468a92264549252004"
OPENWEATHER_API_KEY = "20dfe5cfb0322eb64995c83dc7e5bfb6"
USGS_BASE_URL = "https://earthquake.usgs.gov/fdsnws/event/1/query"

# 📍 Step 3: Get and validate location from user

from geopy.geocoders import OpenCage
from geopy.exc import GeocoderTimedOut

def get_coordinates(location):
    geolocator = OpenCage(OPENCAGE_API_KEY)
    try:
        location_data = geolocator.geocode(location)
        if location_data:
            return location_data.latitude, location_data.longitude
        else:
            return None
    except GeocoderTimedOut:
        return None

user_location = input("📍 Enter a location for climate risk assessment: ")
coordinates = get_coordinates(user_location)

if not coordinates:
    print("❌ Invalid location. Please try again.")
else:
    lat, lon = coordinates
    print(f"✅ Coordinates for {user_location}: {lat}, {lon}")

# 📈 Step 4: Fetch Historical Weather Data
import requests
import pandas as pd
from datetime import datetime, timedelta

def fetch_past_weather(lat, lon, days=30):
    base_url = "http://api.weatherapi.com/v1/history.json"
    end_date = datetime.today()
    records = []

    for i in range(days):
        date = (end_date - timedelta(days=i)).strftime('%Y-%m-%d')
        params = {
            "key": WEATHER_API_KEY,
            "q": f"{lat},{lon}",
            "dt": date
        }
        response = requests.get(base_url, params=params)
        if response.status_code == 200:
            data = response.json()
            day_data = data['forecast']['forecastday'][0]['day']
            records.append({
                "date": date,
                "avg_temp_c": day_data['avgtemp_c'],
                "precip_mm": day_data['totalprecip_mm']
            })

    return pd.DataFrame(records)

weather_df = fetch_past_weather(lat, lon)
weather_df['date'] = pd.to_datetime(weather_df['date'])
print("📊 Sample Historical Weather Data:")
print(weather_df.head())

# ⏳ Step 5: Forecasting using Facebook Prophet
from prophet import Prophet
import matplotlib.pyplot as plt

# Forecast temperature
temp_df = weather_df[['date', 'avg_temp_c']].rename(columns={"date": "ds", "avg_temp_c": "y"})
model_temp = Prophet()
model_temp.fit(temp_df)
future_temp = model_temp.make_future_dataframe(periods=7)
forecast_temp = model_temp.predict(future_temp)

# Plot
model_temp.plot(forecast_temp)
plt.title("🌡️ Forecasted Avg Temperature (Next 7 Days)")
plt.show()

# Flag heatwave risk if temperature > 40°C
forecast_temp['heatwave_risk'] = forecast_temp['yhat'] > 40
print("⚠️ Predicted Heatwave Risk:\n", forecast_temp[['ds', 'yhat', 'heatwave_risk']].tail(7))

# 🌦️ Step 4: Get current weather data

import requests

def get_weather_data(lat, lon):
    url = f"http://api.weatherapi.com/v1/current.json?key={WEATHER_API_KEY}&q={lat},{lon}"
    response = requests.get(url)
    return response.json()

weather_data = get_weather_data(lat, lon)
print("🌡️ Weather Info:")
print(weather_data['current'])

# 🌍 Step 5: Get USGS earthquake data from the past 5 years

import datetime

def get_usgs_earthquake_data(lat, lon, radius_km=100):
    end_time = datetime.date.today()
    start_time = end_time - datetime.timedelta(days=365*5)
    url = (
        f"{USGS_BASE_URL}?format=geojson&starttime={start_time}&endtime={end_time}"
        f"&latitude={lat}&longitude={lon}&maxradiuskm={radius_km}"
    )
    response = requests.get(url)
    return response.json()

earthquake_data = get_usgs_earthquake_data(lat, lon)
print(f"🌋 Earthquakes in the past 5 years within 100km: {len(earthquake_data['features'])}")

# 📈 Step 6: Prepare data for LSTM-based climate forecasting

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

# Example: Generating dummy temperature data for 50 years (monthly data)
months = pd.date_range(start="1970-01-01", end="2020-12-01", freq='M')
temperature_data = np.random.normal(loc=15, scale=5, size=len(months))  # Fake data, replace with real

df = pd.DataFrame({'Date': months, 'Temperature': temperature_data})
df.set_index('Date', inplace=True)

# Visualize the data
df['Temperature'].plot(figsize=(10, 6))
plt.title("Monthly Average Temperature (1970-2020)")
plt.ylabel("Temperature (°C)")
plt.show()

# Normalize the temperature data to scale between 0 and 1
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df[['Temperature']])

# Create the dataset for LSTM (use past 12 months to predict next month)
def create_dataset(data, time_step=12):
    X, y = [], []
    for i in range(time_step, len(data)):
        X.append(data[i-time_step:i, 0])  # Last 12 months
        y.append(data[i, 0])  # Temperature next month
    return np.array(X), np.array(y)

X, y = create_dataset(scaled_data)

# Reshape input data for LSTM [samples, time steps, features]
X = X.reshape(X.shape[0], X.shape[1], 1)

# Split data into training and test sets
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# 🧠 Step 7: Build and train the LSTM model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Build LSTM Model
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(LSTM(units=50, return_sequences=False))
model.add(Dense(units=1))  # Predicting one value (next month's temperature)

model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

from transformers import pipeline

from transformers import pipeline

# Initialize the Hugging Face model pipeline for text generation (adjust model as needed)
risk_assessor_model = pipeline("text-generation", model="gpt2")

def risk_assessor(prompt, max_length=200, do_sample=True, temperature=0.7):
    """
    This function uses a language model to generate a climate risk assessment based on the input prompt.
    """
    print(f"Risk Assessor called with prompt: {prompt}")
    try:
        response = risk_assessor_model(prompt, max_length=max_length, do_sample=do_sample, temperature=temperature)
        return response
    except Exception as e:
        print(f"Error generating response: {str(e)}")
        return None

# 🗓️ Step 8: Predict future temperatures and generate a climate risk scenario

# Example of using predicted temperatures for climate risk projection
future_temperatures = [30, 31, 32]  # Example future temperatures (from your prediction model)

# Projection context for climate risk
projection_context = f"""
By 2040, the average temperature in {user_location} is projected to rise from {weather_data['current']['temp_c']:.2f}°C to {future_temperatures[-1]:.2f}°C.
"""

# Call the risk assessor (AI model) to generate the risk scenario
projection_response = risk_assessor(
    f"{projection_context}\nPossible climate-related impacts include:",
    max_length=250,
    do_sample=True,
    temperature=0.85
)

if projection_response:
    print("🌍 Future Climate Risk Scenario:\n")
    print(projection_response[0]['generated_text'])

# 🗺️ Step 9: Create Interactive Map with Risk Levels

import folium

# 🟢🟡🔴 Define risk level logic
def classify_risk(temp, quakes):
    if temp < 25 and quakes < 5:
        return "Low", "green"
    elif temp < 30 and quakes < 15:
        return "Medium", "orange"
    else:
        return "High", "red"

risk_level, color = classify_risk(weather_data['current']['temp_c'], len(earthquake_data['features']))

# 🌍 Create folium map
m = folium.Map(location=[lat, lon], zoom_start=6)

# Add marker with tooltip and popup
tooltip = f"{user_location} ({risk_level} Risk)"
popup_text = f"<b>Location:</b> {user_location}<br><b>Temperature:</b> {weather_data['current']['temp_c']}°C<br><b>Earthquakes:</b> {len(earthquake_data['features'])}<br><b>Risk Level:</b> {risk_level}"

folium.CircleMarker(
    location=[lat, lon],
    radius=10,
    color=color,
    fill=True,
    fill_color=color,
    fill_opacity=0.7,
    tooltip=tooltip,
    popup=popup_text,
).add_to(m)

m

# 🌫 Step 10: Real-Time Air Quality Index (AQI)

def get_air_quality(lat, lon):
    url = f"http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={OPENWEATHER_API_KEY}"
    data = requests.get(url).json()
    aqi = data['list'][0]['main']['aqi']
    aqi_map = {
        1: "Good",
        2: "Fair",
        3: "Moderate",
        4: "Poor",
        5: "Very Poor"
    }
    return aqi, aqi_map[aqi]

aqi_val, aqi_desc = get_air_quality(lat, lon)
print(f"🫁 Air Quality in {user_location}: {aqi_desc} (AQI {aqi_val})")

# 🌊 Step 11: Elevation-Based Flood Risk

def get_elevation(lat, lon):
    url = f"https://api.open-elevation.com/api/v1/lookup?locations={lat},{lon}"
    response = requests.get(url).json()
    elevation = response['results'][0]['elevation']
    return elevation

elevation = get_elevation(lat, lon)
flood_risk = "High" if elevation < 20 else "Medium" if elevation < 100 else "Low"
print(f"🌊 Elevation: {elevation}m — Flood Risk: {flood_risk}")

# 💬 Chatbot for Climate Q&A

import ipywidgets as widgets
from IPython.display import display, clear_output

chat_history = widgets.Output()

user_input = widgets.Text(
    placeholder='Ask me anything about climate risks here...',
    description='You:',
    layout=widgets.Layout(width='100%')
)

send_button = widgets.Button(
    description='Send',
    button_style='info',
    tooltip='Send your question',
    icon='paper-plane'
)

def chatbot_response(change=None):
    question = user_input.value.strip()
    if not question:
        return

    with chat_history:
        print(f"👤 You: {question}")
        try:
            reply = risk_assessor(
                f"{question}\n(Location: {user_location}, Temp: {weather_data['current']['temp_c']}°C, Elev: {elevation}m, Quakes: {len(earthquake_data['features'])})",
                max_length=200,
                do_sample=True,
                temperature=0.8
            )[0]['generated_text']
            print(f"🤖 AI: {reply}\n")
        except Exception as e:
            print("❌ Sorry, there was an error processing your request.")
            print(str(e))

    user_input.value = ''

send_button.on_click(chatbot_response)
user_input.on_submit(chatbot_response)

chat_ui = widgets.VBox([
    chat_history,
    widgets.HBox([user_input, send_button])
])

# 💬 Chatbot for Climate Q&A

import ipywidgets as widgets
from IPython.display import display, clear_output

chat_history = widgets.Output()

user_input = widgets.Text(
    placeholder='Ask me anything about climate risks here...',
    description='You:',
    layout=widgets.Layout(width='100%')
)

send_button = widgets.Button(
    description='Send',
    button_style='info',
    tooltip='Send your question',
    icon='paper-plane'
)

def chatbot_response(change=None):
    question = user_input.value.strip()
    if not question:
        return

    with chat_history:
        print(f"👤 You: {question}")
        try:
            reply = risk_assessor(
                f"{question}\n(Location: {user_location}, Temp: {weather_data['current']['temp_c']}°C, Elev: {elevation}m, Quakes: {len(earthquake_data['features'])})",
                max_length=200,
                do_sample=True,
                temperature=0.8
            )[0]['generated_text']
            print(f"🤖 AI: {reply}\n")
        except Exception as e:
            print("❌ Sorry, there was an error processing your request.")
            print(str(e))

    user_input.value = ''

send_button.on_click(chatbot_response)
user_input.on_submit(chatbot_response)

chat_ui = widgets.VBox([
    chat_history,
    widgets.HBox([user_input, send_button])
])

# ✅ Function to build the final dashboard UI

def display_dashboard():
    # Rebuild all sections from latest data
    location_info = f"""
    **Location:** {user_location}
    **Latitude:** {lat}
    **Longitude:** {lon}
    """

    weather_info = f"""
    **Temperature:** {weather_data['current']['temp_c']} °C
    **Condition:** {weather_data['current']['condition']['text']}
    **Wind Speed:** {weather_data['current']['wind_kph']} km/h
    **Humidity:** {weather_data['current']['humidity']}%
    """

    aqi_info = f"""
    **AQI Level:** {aqi_val}
    **Description:** {aqi_desc}
    """

    earthquake_info = f"""
    **Earthquakes (last 5 years within 100km):** {len(earthquake_data['features'])}
    """

    flood_info = f"""
    **Elevation:** {elevation} m
    **Flood Risk Level:** {flood_risk}
    """

    forecast_info = f"""
    **Predicted 2040 Temperature:** {future_temperatures[-1]:.2f} °C
    **Temperature Increase:** {future_temperatures[-1] - weather_data['current']['temp_c']:.2f} °C
    """

    risk_info = f"""
    **Risk Level:** {risk_level.upper()}
    **Visual Code:** {color.capitalize()}
    """

    ai_projection = projection_response[0]['generated_text']

    # 👇 Chatbot (defined previously)
    chatbot_tab = widgets.VBox([
        chat_scroll,
        widgets.HBox([user_input, send_button])
    ])

    # Final tab structure
    tab_contents = [
        ("📍 Location", location_info),
        ("🌦️ Weather", weather_info),
        ("🫁 Air Quality", aqi_info),
        ("🌋 Earthquakes", earthquake_info),
        ("🌊 Flood Risk", flood_info),
        ("🌡️ Forecast", forecast_info),
        ("🧠 AI Analysis", ai_projection),
        ("⚠️ Risk Level", risk_info),
        ("💬 Chatbot", chatbot_tab)
    ]

    children = [
        widgets.HTML(f"<pre>{content}</pre>") if isinstance(content, str) else content
        for _, content in tab_contents
    ]

    tabs = widgets.Tab()
    tabs.children = children

    for i, (title, _) in enumerate(tab_contents):
        tabs.set_title(i, title)

    display(Markdown("## 🔍 Climate Risk Summary Dashboard"))
    display(tabs)

# 💬 Chatbot UI Components (must be defined before calling display_dashboard)

import ipywidgets as widgets
from IPython.display import display, clear_output

chat_output = widgets.Output()
chat_scroll = widgets.Box([chat_output], layout=widgets.Layout(overflow='auto', max_height='300px'))

user_input = widgets.Text(
    placeholder='Ask something about this location...',
    layout=widgets.Layout(flex='1 1 auto', width='auto')
)

send_button = widgets.Button(
    icon='paper-plane',
    button_style='primary',
    tooltip='Send',
    layout=widgets.Layout(width='80px')
)

def on_chat_submit(change=None):
    question = user_input.value.strip()
    if not question:
        return

    with chat_output:
        print(f"👤 You: {question}")
        try:
            ai_response = risk_assessor(
                f"{question}\n(Location: {user_location}, Temp: {weather_data['current']['temp_c']}°C, Elev: {elevation}m, Quakes: {len(earthquake_data['features'])})",
                max_length=200,
                do_sample=True,
                temperature=0.8
            )[0]['generated_text']
            print(f"🤖 AI: {ai_response}\n")
        except Exception as e:
            print("❌ Error:", str(e))

    user_input.value = ''

send_button.on_click(on_chat_submit)
user_input.on_submit(on_chat_submit)

from IPython.display import display, Markdown
import ipywidgets as widgets

# ✅ Final dashboard function with elegant formatting and layout
def display_dashboard():
    # Sections with nicely formatted Markdown
    location_info = f"""
### 📍 Location Info
- **City:** {user_location}
- **Latitude:** `{lat}`
- **Longitude:** `{lon}`
"""

    weather_info = f"""
### 🌦️ Current Weather
- **Temperature:** `{weather_data['current']['temp_c']} °C`
- **Condition:** `{weather_data['current']['condition']['text']}`
- **Wind Speed:** `{weather_data['current']['wind_kph']} km/h`
- **Humidity:** `{weather_data['current']['humidity']}%`
"""

    aqi_info = f"""
### 🫁 Air Quality Index
- **AQI Level:** `{aqi_val}`
- **Description:** `{aqi_desc}`
"""

    earthquake_info = f"""
### 🌋 Seismic Activity
- **Earthquakes (last 5 years within 100km):** `{len(earthquake_data['features'])}`
"""

    flood_info = f"""
### 🌊 Flood & Elevation
- **Elevation:** `{elevation} m`
- **Flood Risk Level:** `{flood_risk}`
"""

    forecast_info = f"""
### 🌡️ Future Temperature Forecast
- **Projected 2040 Temp:** `{future_temperatures[-1]:.2f} °C`
- **Increase since today:** `{future_temperatures[-1] - weather_data['current']['temp_c']:.2f} °C`
"""

    risk_info = f"""
### ⚠️ Climate Risk Summary
- **Risk Level:** `{risk_level.upper()}`
- **Color Code:** `{color.capitalize()}`
"""

    ai_analysis = f"""
### 🧠 AI Climate Risk Assessment
{projection_response[0]['generated_text']}
"""

    # ⬇️ Chatbot Box Tab
    chatbot_tab = widgets.VBox([
        widgets.HTML("<b>💬 Climate Chat Assistant</b>"),
        chat_scroll,
        widgets.HBox([user_input, send_button])
    ])

    # Tabs setup
    tab_contents = [
        ("📍 Location", location_info),
        ("🌦️ Weather", weather_info),
        ("🫁 Air Quality", aqi_info),
        ("🌋 Earthquakes", earthquake_info),
        ("🌊 Flood Risk", flood_info),
        ("🌡️ Forecast", forecast_info),
        ("🧠 AI Analysis", ai_analysis),
        ("⚠️ Risk Level", risk_info),
        ("💬 Chatbot", chatbot_tab)
    ]

    # Format the contents into HTML or widgets
    children = [
        widgets.HTML(value=f"<div style='padding:10px;'>{Markdown(content).data}</div>") if isinstance(content, str)
        else content
        for _, content in tab_contents
    ]

    # Create Tab UI
    tabs = widgets.Tab()
    tabs.children = children

    for i, (title, _) in enumerate(tab_contents):
        tabs.set_title(i, title)

    # Display Header and Tabs
    display(Markdown("## 🔍 Climate Risk Summary Dashboard"))
    display(tabs)

# 🚀 Show the UI
display_dashboard()